const CONFIG = {
  // API KEY https://www.themoviedb.org
  KEY: process.env.API_KEY_TMDB,
  BASE_URL: process.env.BASE_URL,
  BASE_IMAGE_URL: `${process.env.BASE_IMAGE_URL}/t/p/w500/`,
  DEFAULT_LANGUAGE: 'en-us',
  // INDEXED DATABASE & PRECACHING SERVICE WORKER
  DATABASE_NAME: process.env.DATABASE_NAME,
  DATABASE_VERSION: process.env.DATABASE_VERSION,
  OBJECT_STORE_NAME: process.env.OBJECT_STORE_NAME,
  //  WSS PUSH NOTIFICATION
  WEB_SOCKET_SERVER: process.env.WEB_SOCKET_SERVER,
  PUSH_MSG_VAPID_PUBLIC_KEY: process.env.PUSH_MSG_VAPID_PUBLIC_KEY,
  PUSH_MSG_SUBSCRIBE_URL: process.env.PUSH_MSG_SUBSCRIBE_URL,
  PUSH_MSG_UNSUBSCRIBE_URL: process.env.PUSH_MSG_UNSUBSCRIBE_URL,
};

export default CONFIG;
